export type ColumnType = "integer" | "text" | "boolean" | "datetime" | "date" | "json";

export interface ColumnDef {
  name: string;
  type: ColumnType;
  nullable: boolean;
  pk?: boolean;
  fk?: string;
  unique?: boolean;
}

export interface TableDef {
  name: string;
  group: "Core" | "System";
  columns: ColumnDef[];
}

export type Row = Record<string, unknown>;
export type TableData = Record<string, Row[]>;

function col(name: string, type: ColumnType, opts: Partial<ColumnDef> = {}): ColumnDef {
  return { name, type, nullable: false, ...opts };
}

// ─── Schema (mirrors the live shadow.db SQLite schema exactly) ─────────────────
export const TABLES: TableDef[] = [
  {
    name: "users",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("name", "text"),
      col("email", "text", { unique: true }),
      col("hashed_password", "text"),
      col("login_attempts", "integer"),
      col("lockout_until", "datetime", { nullable: true }),
      col("bio", "text", { nullable: true }),
      col("email_verified", "boolean"),
      col("verification_email_sent_at", "datetime", { nullable: true }),
      col("is_active", "boolean"),
      col("created_at", "datetime"),
    ],
  },
  {
    name: "goals",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("user_id", "integer", { fk: "users.id" }),
      col("position", "integer"),
      col("title", "text"),
      col("summary", "text"),
      col("category", "text"),
      col("status", "text"),
      col("motivation", "text"),
      col("success_definition", "text"),
      col("current_state", "text"),
      col("challenges", "json"),
      col("strengths", "json"),
      col("success_metrics", "json"),
      col("insights", "json"),
      col("target_date", "date"),
      col("paused_at", "datetime", { nullable: true }),
      col("completed_at", "datetime", { nullable: true }),
      col("milestones_total", "integer"),
      col("milestones_completed", "integer"),
      col("habits_total", "integer"),
      col("habits_active", "integer"),
      col("created_at", "datetime"),
      col("updated_at", "datetime"),
      col("source_conversation_id", "integer", { nullable: true, fk: "conversations.id" }),
    ],
  },
  {
    name: "milestones",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("goal_id", "integer", { fk: "goals.id" }),
      col("user_id", "integer", { fk: "users.id" }),
      col("title", "text"),
      col("description", "text", { nullable: true }),
      col("status", "text"),
      col("reason", "text", { nullable: true }),
      col("estimated_duration_days", "integer", { nullable: true }),
      col("started_at", "datetime", { nullable: true }),
      col("paused_at", "datetime", { nullable: true }),
      col("cancelled_at", "datetime", { nullable: true }),
      col("target_date", "date", { nullable: true }),
      col("completed_at", "datetime", { nullable: true }),
      col("position", "integer"),
      col("created_at", "datetime"),
      col("created_by", "text"),
      col("assistant_context", "json", { nullable: true }),
      col("total_tasks", "integer"),
      col("completed_tasks", "integer"),
    ],
  },
  {
    name: "tasks",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("goal_id", "integer", { fk: "goals.id" }),
      col("user_id", "integer", { fk: "users.id" }),
      col("milestone_id", "integer", { fk: "milestones.id" }),
      col("title", "text"),
      col("task_type", "text"),
      col("status", "text"),
      col("current_value", "integer", { nullable: true }),
      col("target_value", "integer", { nullable: true }),
      col("value_unit", "text", { nullable: true }),
      col("planning_enabled", "boolean"),
      col("tracking_enabled", "boolean"),
      col("planner_type", "text"),
      col("planner_target", "integer", { nullable: true }),
      col("frequencies", "json"),
      col("priority", "text"),
      col("preferred_time", "text"),
      col("specific_time", "text", { nullable: true }),
      col("duration_minutes", "integer", { nullable: true }),
      col("weekly_count", "integer", { nullable: true }),
      col("monthly_count", "integer", { nullable: true }),
      col("specific_days", "json", { nullable: true }),
      col("day_fallback", "boolean"),
      col("assistant_context", "json", { nullable: true }),
      col("note", "text", { nullable: true }),
      col("position", "integer"),
      col("created_at", "datetime"),
      col("created_by", "text"),
      col("started_at", "datetime", { nullable: true }),
      col("paused_at", "datetime", { nullable: true }),
      col("completed_at", "datetime", { nullable: true }),
      col("cancelled_at", "datetime", { nullable: true }),
    ],
  },
  {
    name: "habits",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("user_id", "integer", { fk: "users.id" }),
      col("goal_id", "integer", { nullable: true, fk: "goals.id" }),
      col("title", "text"),
      col("note", "text", { nullable: true }),
      col("frequencies", "json"),
      col("preferred_time", "text"),
      col("specific_time", "text", { nullable: true }),
      col("duration_minutes", "integer", { nullable: true }),
      col("start_date", "date", { nullable: true }),
      col("end_date", "date", { nullable: true }),
      col("weekly_count", "integer", { nullable: true }),
      col("monthly_count", "integer", { nullable: true }),
      col("specific_days", "json", { nullable: true }),
      col("day_fallback", "boolean"),
      col("priority", "text"),
      col("status", "text"),
      col("created_at", "datetime"),
      col("updated_at", "datetime"),
      col("planner_type", "text"),
      col("planner_target", "integer", { nullable: true }),
      col("value_unit", "text", { nullable: true }),
      col("category", "text", { nullable: true }),
      col("tracking_enabled", "boolean"),
    ],
  },
  {
    name: "yearly_tasks",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("user_id", "integer", { fk: "users.id" }),
      col("goal_id", "integer", { nullable: true, fk: "goals.id" }),
      col("title", "text"),
      col("note", "text", { nullable: true }),
      col("category", "text", { nullable: true }),
      col("planner_type", "text"),
      col("planner_target", "integer", { nullable: true }),
      col("value_unit", "text", { nullable: true }),
      col("priority", "text"),
      col("recurrence_month", "integer"),
      col("recurrence_day", "integer"),
      col("preferred_time", "text"),
      col("specific_time", "text", { nullable: true }),
      col("allow_snoozing", "boolean"),
      col("snooze_limit", "integer", { nullable: true }),
      col("duration_minutes", "integer", { nullable: true }),
      col("created_at", "datetime"),
      col("updated_at", "datetime"),
    ],
  },
  {
    name: "scheduled_tasks",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("user_id", "integer", { fk: "users.id" }),
      col("goal_id", "integer", { nullable: true, fk: "goals.id" }),
      col("title", "text"),
      col("note", "text", { nullable: true }),
      col("category", "text", { nullable: true }),
      col("planner_type", "text"),
      col("planner_target", "integer", { nullable: true }),
      col("value_unit", "text", { nullable: true }),
      col("priority", "text"),
      col("scheduled_date", "date"),
      col("preferred_time", "text"),
      col("specific_time", "text", { nullable: true }),
      col("allow_snoozing", "boolean"),
      col("snooze_limit", "integer", { nullable: true }),
      col("duration_minutes", "integer", { nullable: true }),
      col("status", "text"),
      col("created_at", "datetime"),
      col("updated_at", "datetime"),
    ],
  },
  {
    name: "plans",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("user_id", "integer", { fk: "users.id" }),
      col("source_type", "text"),
      col("source_id", "integer"),
      col("title", "text"),
      col("planner_type", "text"),
      col("planner_target", "integer", { nullable: true }),
      col("value_unit", "text", { nullable: true }),
      col("frequencies", "json"),
      col("weekly_count", "integer", { nullable: true }),
      col("monthly_count", "integer", { nullable: true }),
      col("specific_days", "json", { nullable: true }),
      col("day_fallback", "boolean"),
      col("preferred_time", "text"),
      col("specific_time", "text", { nullable: true }),
      col("duration_minutes", "integer", { nullable: true }),
      col("priority", "text"),
      col("start_date", "date", { nullable: true }),
      col("end_date", "date", { nullable: true }),
      col("status", "text"),
      col("created_at", "datetime"),
      col("updated_at", "datetime"),
    ],
  },
  {
    name: "plan_records",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("user_id", "integer", { fk: "users.id" }),
      col("plan_id", "integer", { nullable: true, fk: "plans.id" }),
      col("source_type", "text", { nullable: true }),
      col("source_id", "integer", { nullable: true }),
      col("scheduled_date", "date"),
      col("title", "text"),
      col("planner_type", "text"),
      col("planner_target", "integer", { nullable: true }),
      col("value_unit", "text", { nullable: true }),
      col("priority", "text"),
      col("preferred_time", "text"),
      col("specific_time", "text", { nullable: true }),
      col("duration_minutes", "integer", { nullable: true }),
      col("status", "text"),
      col("actual_value", "integer"),
      col("note", "text", { nullable: true }),
      col("completed_at", "datetime", { nullable: true }),
      col("created_at", "datetime"),
      col("updated_at", "datetime"),
    ],
  },
  {
    name: "reports",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("user_id", "integer", { fk: "users.id" }),
      col("report_date", "date"),
      col("report_type", "text"),
      col("generated_at", "datetime"),
      col("alignment_score", "integer"),
      col("headline", "text"),
      col("summary", "text"),
      col("stats", "json"),
      col("goals", "json"),
      col("highlights", "json"),
      col("closing", "json"),
      col("model_used", "text", { nullable: true }),
      col("created_at", "datetime"),
    ],
  },
  {
    name: "daily_briefs",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("notification_id", "integer", { fk: "notifications.id" }),
      col("user_id", "integer", { fk: "users.id" }),
      col("brief_date", "date"),
      col("complete_brief", "text"),
      col("created_at", "datetime"),
    ],
  },
  {
    name: "conversations",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("user_id", "integer", { fk: "users.id" }),
      col("title", "text"),
      col("agent_type", "text"),
      col("stable_context", "text"),
      col("context_summary", "text"),
      col("summary_user_message_count", "integer"),
      col("memory_user_message_count", "integer"),
      col("linked_items", "json"),
      col("created_at", "datetime"),
      col("updated_at", "datetime"),
    ],
  },
  {
    name: "messages",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("conversation_id", "integer", { fk: "conversations.id" }),
      col("role", "text"),
      col("content", "json"),
      col("request_status", "text"),
      col("linked_items", "json"),
      col("created_at", "datetime"),
    ],
  },
  {
    name: "user_memories",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("user_id", "integer", { fk: "users.id" }),
      col("memory_type", "text"),
      col("topic", "text"),
      col("content", "json"),
      col("created_at", "datetime"),
      col("updated_at", "datetime"),
    ],
  },
  {
    name: "user_settings",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("user_id", "integer", { fk: "users.id", unique: true }),
      col("appearance", "json"),
      col("notifications", "json"),
      col("ai_behavior", "json"),
      col("planner", "json"),
      col("privacy", "json"),
      col("accessibility", "json"),
      col("updated_at", "datetime"),
    ],
  },
  {
    name: "goal_proposals",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("proposal_id", "text", { unique: true }),
      col("user_id", "integer", { fk: "users.id" }),
      col("conversation_id", "integer", { fk: "conversations.id" }),
      col("message_id", "integer", { fk: "messages.id" }),
      col("content_index", "integer"),
      col("status", "text"),
      col("goal_id", "integer", { nullable: true, fk: "goals.id" }),
      col("created_at", "datetime"),
      col("updated_at", "datetime"),
    ],
  },
  {
    name: "milestone_proposals",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("proposal_id", "text", { unique: true }),
      col("user_id", "integer", { fk: "users.id" }),
      col("conversation_id", "integer", { fk: "conversations.id" }),
      col("message_id", "integer", { fk: "messages.id" }),
      col("content_index", "integer"),
      col("status", "text"),
      col("goal_id", "integer", { nullable: true, fk: "goals.id" }),
      col("milestone_id", "integer", { nullable: true, fk: "milestones.id" }),
      col("created_at", "datetime"),
      col("updated_at", "datetime"),
    ],
  },
  {
    name: "scheduled_task_proposals",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("proposal_id", "text", { unique: true }),
      col("user_id", "integer", { fk: "users.id" }),
      col("conversation_id", "integer", { fk: "conversations.id" }),
      col("message_id", "integer", { fk: "messages.id" }),
      col("content_index", "integer"),
      col("status", "text"),
      col("scheduled_task_id", "integer", { nullable: true, fk: "scheduled_tasks.id" }),
      col("created_at", "datetime"),
      col("updated_at", "datetime"),
    ],
  },
  {
    name: "task_proposals",
    group: "Core",
    columns: [
      col("id", "integer", { pk: true }),
      col("proposal_id", "text", { unique: true }),
      col("user_id", "integer", { fk: "users.id" }),
      col("conversation_id", "integer", { fk: "conversations.id" }),
      col("message_id", "integer", { fk: "messages.id" }),
      col("content_index", "integer"),
      col("status", "text"),
      col("goal_id", "integer", { nullable: true, fk: "goals.id" }),
      col("milestone_id", "integer", { nullable: true, fk: "milestones.id" }),
      col("task_id", "integer", { nullable: true, fk: "tasks.id" }),
      col("created_at", "datetime"),
      col("updated_at", "datetime"),
    ],
  },
  {
    name: "active_sessions",
    group: "System",
    columns: [
      col("id", "integer", { pk: true }),
      col("user_id", "integer", { fk: "users.id" }),
      col("device_name", "text"),
      col("custom_name", "text", { nullable: true }),
      col("browser", "text"),
      col("os_name", "text"),
      col("ip_address", "text", { nullable: true }),
      col("refresh_token_hash", "text", { nullable: true }),
      col("confirmed", "boolean"),
      col("last_seen_at", "datetime"),
      col("created_at", "datetime"),
    ],
  },
  {
    name: "ip_rate_limits",
    group: "System",
    columns: [
      col("ip", "text", { pk: true }),
      col("kind", "text", { pk: true }),
      col("attempts", "integer"),
      col("lockout_until", "datetime", { nullable: true }),
      col("window_start", "datetime", { nullable: true }),
    ],
  },
  {
    name: "push_subscriptions",
    group: "System",
    columns: [
      col("id", "integer", { pk: true }),
      col("user_id", "integer", { fk: "users.id" }),
      col("endpoint", "text", { unique: true }),
      col("p256dh", "text"),
      col("auth", "text"),
      col("user_agent", "text", { nullable: true }),
      col("created_at", "datetime"),
    ],
  },
  {
    name: "notifications",
    group: "System",
    columns: [
      col("id", "integer", { pk: true }),
      col("priority", "integer"),
      col("user_id", "integer", { fk: "users.id" }),
      col("title", "text"),
      col("body", "text", { nullable: true }),
      col("type", "text"),
      col("level", "integer"),
      col("read", "boolean"),
      col("emailed", "boolean"),
      col("url", "text", { nullable: true }),
      col("event_key", "text", { nullable: true }),
      col("created_at", "datetime"),
    ],
  },
];

export function getTable(name: string): TableDef | undefined {
  return TABLES.find((t) => t.name === name);
}

export function pkColumns(table: TableDef): ColumnDef[] {
  return table.columns.filter((c) => c.pk);
}

// Stable identity string for a row — handles composite PKs (e.g. ip_rate_limits: ip+kind).
export function rowKey(table: TableDef, row: Row): string {
  return pkColumns(table).map((c) => String(row[c.name])).join("::");
}

// Human-friendly label for a row's identity, used in confirm dialogs / modal titles.
export function rowLabel(table: TableDef, row: Row): string {
  const pks = pkColumns(table);
  if (pks.length === 1) return `#${String(row[pks[0].name])}`;
  return pks.map((c) => `${c.name}=${String(row[c.name])}`).join(", ");
}

// ─── Mock data (matches Shadow's real seed data / recent screenshots) ──────────
export const MOCK_ROWS: Record<string, Row[]> = {
  users: [
    {
      id: 1, name: "Harsh Gupta", email: "harsh@shadowassistant.in",
      hashed_password: "••••••••••••••••", login_attempts: 0, lockout_until: null,
      bio: "Building Shadow, one habit at a time.", email_verified: true,
      verification_email_sent_at: null, is_active: true, created_at: "2026-06-02 09:14:00",
    },
  ],
  goals: [
    {
      id: 1, user_id: 1, position: 0, title: "Ship Shadow V2",
      summary: "Launch the rebuilt planner with AI coaching baked in.",
      category: "Career", status: "Active",
      motivation: "Prove the new architecture scales past V1's limits.",
      success_definition: "V2 live for all users with feature parity + AI reports.",
      current_state: "Core planner shipped, AI reports in progress.",
      challenges: ["Scope creep", "Time management"], strengths: ["Fast iteration", "Clear vision"],
      success_metrics: ["Weekly active users", "Report generation rate"], insights: ["Ship smaller slices"],
      target_date: "2026-12-31", paused_at: null, completed_at: null,
      milestones_total: 4, milestones_completed: 1, habits_total: 3, habits_active: 3,
      created_at: "2026-06-05 10:00:00", updated_at: "2026-09-15 08:30:00", source_conversation_id: null,
    },
    {
      id: 2, user_id: 1, position: 1, title: "Get back in shape",
      summary: "Rebuild a consistent fitness routine after a busy launch quarter.",
      category: "Health", status: "Active",
      motivation: "More energy for deep work.", success_definition: "Train 4x/week for 8 weeks straight.",
      current_state: "2 sessions/week currently.", challenges: ["Late nights"], strengths: ["Enjoys running"],
      success_metrics: ["Sessions per week"], insights: ["Morning slots stick better"],
      target_date: "2026-11-30", paused_at: null, completed_at: null,
      milestones_total: 3, milestones_completed: 2, habits_total: 2, habits_active: 2,
      created_at: "2026-07-01 07:00:00", updated_at: "2026-09-10 19:20:00", source_conversation_id: 2,
    },
  ],
  milestones: [
    { id: 1, goal_id: 1, user_id: 1, title: "Auth + Core Planner", description: "Ship login, tasks, habits, schedule.", status: "Completed", reason: null, estimated_duration_days: 30, started_at: "2026-06-05 10:00:00", paused_at: null, cancelled_at: null, target_date: "2026-07-05", completed_at: "2026-07-02 18:00:00", position: 0, created_at: "2026-06-05 10:00:00", created_by: "User", assistant_context: null, total_tasks: 6, completed_tasks: 6 },
    { id: 2, goal_id: 1, user_id: 1, title: "AI Reports & Insights", description: "Daily/weekly report generation via LLM.", status: "In Progress", reason: null, estimated_duration_days: 21, started_at: "2026-08-01 09:00:00", paused_at: null, cancelled_at: null, target_date: "2026-09-25", completed_at: null, position: 1, created_at: "2026-06-05 10:00:00", created_by: "User", assistant_context: null, total_tasks: 4, completed_tasks: 2 },
    { id: 3, goal_id: 1, user_id: 1, title: "BackOffice Admin Panel", description: "Deploy/DB/Server management UI.", status: "In Progress", reason: null, estimated_duration_days: 14, started_at: "2026-09-10 09:00:00", paused_at: null, cancelled_at: null, target_date: "2026-09-30", completed_at: null, position: 2, created_at: "2026-06-05 10:00:00", created_by: "Assistant", assistant_context: { source: "goal_coach" }, total_tasks: 3, completed_tasks: 1 },
    { id: 4, goal_id: 2, user_id: 1, title: "Build the habit", description: "Get to 4 sessions/week consistently.", status: "In Progress", reason: null, estimated_duration_days: 56, started_at: "2026-07-01 07:00:00", paused_at: null, cancelled_at: null, target_date: "2026-08-26", completed_at: null, position: 0, created_at: "2026-07-01 07:00:00", created_by: "User", assistant_context: null, total_tasks: 2, completed_tasks: 2 },
  ],
  tasks: [
    { id: 1, goal_id: 1, user_id: 1, milestone_id: 3, title: "Build Deploy page", task_type: "Binary", status: "Completed", current_value: null, target_value: null, value_unit: null, planning_enabled: false, tracking_enabled: false, planner_type: "simple", planner_target: null, frequencies: [], priority: "high", preferred_time: "flexible", specific_time: null, duration_minutes: null, weekly_count: null, monthly_count: null, specific_days: null, day_fallback: false, assistant_context: null, note: null, position: 0, created_at: "2026-09-10 09:00:00", created_by: "User", started_at: "2026-09-10 09:00:00", paused_at: null, completed_at: "2026-09-17 17:00:00", cancelled_at: null },
    { id: 2, goal_id: 1, user_id: 1, milestone_id: 3, title: "Build Database page", task_type: "Binary", status: "In Progress", current_value: null, target_value: null, value_unit: null, planning_enabled: false, tracking_enabled: false, planner_type: "simple", planner_target: null, frequencies: [], priority: "high", preferred_time: "flexible", specific_time: null, duration_minutes: null, weekly_count: null, monthly_count: null, specific_days: null, day_fallback: false, assistant_context: null, note: "Includes table browser + SQL console.", position: 1, created_at: "2026-09-10 09:00:00", created_by: "User", started_at: "2026-09-18 09:00:00", paused_at: null, completed_at: null, cancelled_at: null },
    { id: 3, goal_id: 1, user_id: 1, milestone_id: 2, title: "Write daily report prompt", task_type: "Binary", status: "Completed", current_value: null, target_value: null, value_unit: null, planning_enabled: false, tracking_enabled: false, planner_type: "simple", planner_target: null, frequencies: [], priority: "medium", preferred_time: "flexible", specific_time: null, duration_minutes: null, weekly_count: null, monthly_count: null, specific_days: null, day_fallback: false, assistant_context: null, note: null, position: 0, created_at: "2026-08-01 09:00:00", created_by: "User", started_at: "2026-08-01 09:00:00", paused_at: null, completed_at: "2026-08-14 12:00:00", cancelled_at: null },
    { id: 4, goal_id: 2, user_id: 1, milestone_id: 4, title: "Run 50km this month", task_type: "Numeric", status: "In Progress", current_value: 32, target_value: 50, value_unit: "km", planning_enabled: true, tracking_enabled: true, planner_type: "metric", planner_target: 12, frequencies: ["weekly"], priority: "medium", preferred_time: "morning", specific_time: "06:30", duration_minutes: 40, weekly_count: 4, monthly_count: null, specific_days: null, day_fallback: true, assistant_context: null, note: null, position: 0, created_at: "2026-07-01 07:00:00", created_by: "User", started_at: "2026-07-01 07:00:00", paused_at: null, completed_at: null, cancelled_at: null },
    { id: 5, goal_id: 2, user_id: 1, milestone_id: 4, title: "Strength train 2x/week", task_type: "Binary", status: "In Progress", current_value: null, target_value: null, value_unit: null, planning_enabled: true, tracking_enabled: true, planner_type: "simple", planner_target: null, frequencies: ["weekly"], priority: "low", preferred_time: "evening", specific_time: "18:00", duration_minutes: 45, weekly_count: 2, monthly_count: null, specific_days: null, day_fallback: false, assistant_context: null, note: null, position: 1, created_at: "2026-07-01 07:00:00", created_by: "User", started_at: "2026-07-01 07:00:00", paused_at: null, completed_at: null, cancelled_at: null },
  ],
  habits: [
    { id: 1, user_id: 1, goal_id: 2, title: "Morning Run", note: null, frequencies: ["weekly"], preferred_time: "morning", specific_time: "06:30", duration_minutes: 30, start_date: "2026-07-01", end_date: null, weekly_count: 4, monthly_count: null, specific_days: null, day_fallback: true, priority: "medium", status: "active", created_at: "2026-07-01 07:00:00", updated_at: "2026-09-15 06:45:00", planner_type: "metric", planner_target: 5, value_unit: "km", category: "Health", tracking_enabled: true },
    { id: 2, user_id: 1, goal_id: null, title: "No junk food", note: "A small appreciation for no junk food week", frequencies: ["weekly"], preferred_time: "evening", specific_time: null, duration_minutes: null, start_date: "2026-08-01", end_date: null, weekly_count: 7, monthly_count: null, specific_days: null, day_fallback: false, priority: "lowest", status: "active", created_at: "2026-08-01 08:00:00", updated_at: "2026-09-14 20:00:00", planner_type: "simple", planner_target: null, value_unit: null, category: "Health", tracking_enabled: false },
    { id: 3, user_id: 1, goal_id: 1, title: "Deep work block", note: null, frequencies: ["weekly"], preferred_time: "morning", specific_time: "09:00", duration_minutes: 120, start_date: "2026-06-05", end_date: null, weekly_count: 5, monthly_count: null, specific_days: null, day_fallback: false, priority: "high", status: "active", created_at: "2026-06-05 10:00:00", updated_at: "2026-09-16 09:05:00", planner_type: "simple", planner_target: null, value_unit: null, category: "Career", tracking_enabled: false },
  ],
  scheduled_tasks: [
    { id: 1, user_id: 1, goal_id: null, title: "Release Party", note: null, category: "Social", planner_type: "simple", planner_target: null, value_unit: null, priority: "medium", scheduled_date: "2026-09-25", preferred_time: "evening", specific_time: "19:00", allow_snoozing: false, snooze_limit: null, duration_minutes: 180, status: "upcoming", created_at: "2026-09-01 10:00:00", updated_at: "2026-09-01 10:00:00" },
    { id: 2, user_id: 1, goal_id: null, title: "Pronto Gourmet Food", note: "A small appreciation for no junk food week", category: "Food", planner_type: "simple", planner_target: null, value_unit: null, priority: "lowest", scheduled_date: "2026-09-20", preferred_time: "evening", specific_time: null, allow_snoozing: true, snooze_limit: 2, duration_minutes: 60, status: "upcoming", created_at: "2026-09-01 10:00:00", updated_at: "2026-09-01 10:00:00" },
    { id: 3, user_id: 1, goal_id: null, title: "Deloitte Course", note: null, category: "Career", planner_type: "simple", planner_target: null, value_unit: null, priority: "medium", scheduled_date: "2026-09-11", preferred_time: "flexible", specific_time: null, allow_snoozing: false, snooze_limit: null, duration_minutes: null, status: "completed", created_at: "2026-09-01 10:00:00", updated_at: "2026-09-11 15:00:00" },
    { id: 4, user_id: 1, goal_id: null, title: "Bike Service", note: null, category: "Errands", planner_type: "simple", planner_target: null, value_unit: null, priority: "medium", scheduled_date: "2026-09-15", preferred_time: "flexible", specific_time: null, allow_snoozing: false, snooze_limit: null, duration_minutes: null, status: "missed", created_at: "2026-09-01 10:00:00", updated_at: "2026-09-16 08:00:00" },
  ],
  plans: [
    { id: 1, user_id: 1, source_type: "habit", source_id: 1, title: "Morning Run", planner_type: "metric", planner_target: 5, value_unit: "km", frequencies: ["weekly"], weekly_count: 4, monthly_count: null, specific_days: null, day_fallback: true, preferred_time: "morning", specific_time: "06:30", duration_minutes: 30, priority: "medium", start_date: "2026-07-01", end_date: null, status: "active", created_at: "2026-07-01 07:00:00", updated_at: "2026-09-15 06:45:00" },
    { id: 2, user_id: 1, source_type: "habit", source_id: 3, title: "Deep work block", planner_type: "simple", planner_target: null, value_unit: null, frequencies: ["weekly"], weekly_count: 5, monthly_count: null, specific_days: null, day_fallback: false, preferred_time: "morning", specific_time: "09:00", duration_minutes: 120, priority: "high", start_date: "2026-06-05", end_date: null, status: "active", created_at: "2026-06-05 10:00:00", updated_at: "2026-09-16 09:05:00" },
  ],
  reports: [
    {
      id: 1, user_id: 1, report_date: "2026-09-17", report_type: "daily", generated_at: "2026-09-18 00:05:00",
      alignment_score: 86, headline: "Strong finish to the week",
      summary: "You closed out 1/1 tasks and 9/16 habits today, extending your streak to 20 days.",
      stats: { tasks_done: 1, habits_done: 9, streak: 20 }, goals: [{ id: 1, progress: 0.6 }],
      highlights: ["Shipped the Deploy page", "Kept the morning run streak alive"],
      closing: { tone: "encouraging" }, model_used: "claude-sonnet-5", created_at: "2026-09-18 00:05:00",
    },
  ],
  daily_briefs: [],
  conversations: [
    { id: 1, user_id: 1, title: "Planning Shadow V2 launch", agent_type: "shadow", stable_context: "", context_summary: "Discussed BackOffice scope and Deploy page design.", summary_user_message_count: 12, memory_user_message_count: 4, linked_items: { goal_id: 1 }, created_at: "2026-09-01 10:00:00", updated_at: "2026-09-18 08:00:00" },
    { id: 2, user_id: 1, title: "Fitness goal check-in", agent_type: "goal_coach", stable_context: "", context_summary: "Reviewed running progress, suggested morning slot.", summary_user_message_count: 6, memory_user_message_count: 2, linked_items: { goal_id: 2 }, created_at: "2026-08-20 07:30:00", updated_at: "2026-09-10 19:20:00" },
  ],
  messages: [],
  user_memories: [],
  user_settings: [
    { id: 1, user_id: 1, appearance: { theme: "dark" }, notifications: { email: true, push: true }, ai_behavior: { tone: "direct" }, planner: { week_starts: "monday" }, privacy: { share_reports: false }, accessibility: { reduce_motion: false }, updated_at: "2026-09-12 11:00:00" },
  ],
  goal_proposals: [],
  milestone_proposals: [],
  scheduled_task_proposals: [],
  task_proposals: [],
  yearly_tasks: [],
  plan_records: [],
  active_sessions: [
    { id: 1, user_id: 1, device_name: "Chrome on Windows", custom_name: "Work laptop", browser: "Chrome 129", os_name: "Windows 11", ip_address: "203.0.113.42", refresh_token_hash: "a1b2c3d4e5f6…", confirmed: true, last_seen_at: "2026-09-18 12:40:00", created_at: "2026-06-02 09:14:00" },
  ],
  ip_rate_limits: [],
  push_subscriptions: [],
  notifications: [],
};
